# Generated by Django 4.1.5 on 2024-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('descritiong', models.CharField(max_length=200)),
            ],
        ),
    ]
